// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Cart: typeof import('./src/components/Cart.vue')['default']
    CheckoutButton: typeof import('./src/components/CheckoutButton.vue')['default']
    Product: typeof import('./src/components/Product.vue')['default']
    Products: typeof import('./src/components/Products.vue')['default']
  }
}

export { }
