// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Card.vue')['default']
    Cart: typeof import('./src/components/Cart.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    Gallery: typeof import('./src/components/Gallery.vue')['default']
    Preview: typeof import('./src/components/Preview.vue')['default']
    Product: typeof import('./src/components/Product.vue')['default']
    Products: typeof import('./src/components/Products.vue')['default']
  }
}

export { }
